name: build adocs

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  adoc_build-dataset:
    runs-on: ubuntu-latest
    name: Asciidoctor conversion, dataset variant
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -D docs -a variant-dataset *.asciidoc *.adoc && echo 'gemini.agi.org.uk' > docs/CNAME"
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with: 
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./docs/