name: build adocs

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  adoc_build-dataset:
    runs-on: ubuntu-latest
    name: Asciidoctor conversion, dataset variant
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build datasets variant
      id: adocbuild-datasets
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -a variant-dataset 'docs/*.asciidoc' 'docs/*.adoc'"
    - name: Build services variant
      id: adocbuild-services
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -a variant-service 'docs/*.asciidoc' 'docs/*.adoc'"
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with: 
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./docs/